### ISSUE TITLE
images not found when running on IKS

### ISSUE THREAD

**Issue by markstur** [watson-developer-cloud/visual-recognition-code-pattern#10]
The included images that you can click on do not work when deploying to IKS.
It tries to find those images under public, but they only exist under build in that container.

**Comment by mamoonraja** [comment]
do you have the `docker` file for the deployment?

**Comment by mamoonraja** [comment]
Joe had a fix out for this https://github.com/watson-developer-cloud/visual-recognition-code-pattern/commit/4b25f57d2f35523add1ff1e2fcab4d9cc1372434, but looks like they have caching issues with starter kit registry and they will update it manually now.

**Comment by mamoonraja** [comment]
The cloud team fixed the issue with `cache`, should be fixed now.
