### ISSUE TITLE
Demo web slow in uploading image and show no result after uploaded image

### ISSUE THREAD

**Issue by someoenthy** [watson-developer-cloud/visual-recognition-code-pattern#13]
https://visual-recognition-code-pattern.ng.bluemix.net/

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by someoenthy** [comment]
1. Go to https://visual-recognition-code-pattern.ng.bluemix.net/ 
2. Upload image, It takes few minutes instead of few seconds
3. Image has been uploaded successfully. But result has not updated according to the picture. 
![image](https://user-images.githubusercontent.com/66547116/88243611-7f9e6f00-ccc3-11ea-8783-3fbce7be9caf.png)

**Comment by mamoonraja** [comment]
@someoenthy I do notice that service is returning `502 Bad gateway`, we do show toast notification of error, not sure if it showed up for you. Anyways, I will take a look and see whats going on. Thanks for bringing this to our attention.

**Comment by someoenthy** [comment]
I saw no error message. I use Firefox and Chrome browser to test this website. You are welcome.
