### ISSUE TITLE
Issue on classifier_ids

### ISSUE THREAD

**Issue by reset-hard** [watson-developer-cloud/visual-recognition-code-pattern#3]
issue on code when try to use other classifier_ids.
as IBM Documentation says:
https://cloud.ibm.com/docs/services/visual-recognition?topic=visual-recognition-getting-started-tutorial&programming_language=javascript

on app.js

need to change
from
```javascript
  const classifyParams = {
    imagesFile: imageFile,
    classifier_ids: ['default'], // not working with 'food'
  };
```

to 

```javascript
  const classifyParams = {
    imagesFile: imageFile,
    classifierIds: ['default'], // working also with 'food'
  };
```

**Comment by mamoonraja** [comment]
Fixed in #4
